# Misc
cache=yes
hwdec=auto

# Subs
sub-auto=fuzzy
slang=ja,jpn,en,eng
sub-font="Noto Sans CJK JP"
sub-font-size=52 # make reading kanji easier
sub-bold=yes # see above
sub-border-color="#000000"
sub-border-size=3
sub-fix-timing=yes

# Audio
alang=ja,jpn
audio-pitch-correction=no

# Playback
keep-open=yes
save-position-on-quit=yes
hr-seek=yes


# Screenshots
screenshot-directory="~/Pictures/Screenshots/"
screenshot-template="%F_%wHh%wMm%wSs%wTms"
screenshot-format=jpg
screenshot-jpeg-quality=90
screenshot-high-bit-depth=yes
